### ISSUE TITLE
Usage with input and append to body

### ISSUE THREAD

**Issue by ArielGueta** [scttcper/ngx-color#1]
Great library, looks really good.

I have two questions:
1. How can I use it with input, I mean when I click on input the picker needs to be shown next to it. 
2. There is an option to append it to the body element? The idea is to use it with elements with overflow hidden. 

Thanks.

**Comment by scttcper** [comment]
Would have to display the component on the input blur event. 
```
<input type="text" [(ngModel)]="myModel" (blur)="onBlurMethod()">
```

Right now can maybe use something like ng-bootstraps popover? https://ng-bootstrap.github.io/#/components/popover/examples

**Comment by ArielGueta** [comment]
Thanks, I hope it will be built in in the future, I guess this is the desired behavior.

**Comment by scttcper** [comment]
There's also https://material.angular.io/cdk/overlay/overview
I can setup an example in the demo since i think others will look for the same thing.

Lets leave it open, its a good idea

**Comment by ArielGueta** [comment]
Thanks !

**Comment by YZahringer** [comment]
Any sample for popover from button/input?

**Comment by sks40gb** [comment]
Its great library. Just missing the popover option. Do you have any ETA on this ?

**Comment by scttcper** [comment]
Still no plans to add popover

**Comment by dsahu75** [comment]
Please can you help with an example when the input is clicked the picker is shown next to or below it.

**Comment by shaktippatel** [comment]
Great library, only missing thing is the popover :)
