### ISSUE TITLE
DIV swatches-picker and swatches-overflow have hardcoded inline style

### ISSUE THREAD

**Issue by PeS82** [scttcper/ngx-color#131]
When using `<color-swatches>` the element has fixed width and height due to inline CSS style attribute.

I believe we should be able to resize that as we see fit based on CSS classes (which are already there but have no chance fighting against `style="width: 320px; height: 240px"`)

Thanks.

P.S. Love the library

**Comment by scttcper** [comment]
they accept a width and height input, let me know if you need something else

https://github.com/scttcper/ngx-color/blob/af7bd67cabcf4dc2965c1425f15e5e3e2da42136/src/lib/components/swatches/swatches.component.ts#L46-L51

**Comment by PeS82** [comment]
Thanks for fast response. Well, what if we want other units than pixels?

Do you mind if I try to make PR?

**Comment by scttcper** [comment]
sure
