### ISSUE TITLE
Troubles setting values for HSL editor

### ISSUE THREAD

**Issue by mmadrigalva** [scttcper/ngx-color#144]
Hello, first of all, thanks for this great library we really appreciate your work.

So, I have a question, and is about a problem that we have when we try to set values to HSL editor.

Here you have the example: https://www.screencast.com/t/oq336Eca6TU

As you could see, HEX and RGB inputs work fine, but on HSL editor, turns values to 0.

Our lines of code are simply like this: 
<color-chrome [disableAlpha]='true' [color]='color' (onChangeComplete)='handleCustomColorChange($event)'></color-chrome>

I really appreciate if you could help us to find which is the error and how we could fix it.

Notes:

Actually, we have the 1.2.1 version, but, we have updated to 2.0.1 and the issue doesn't go out

**Comment by scttcper** [comment]
thanks for reporting should be fixed in 
https://github.com/scttcper/ngx-color/releases/tag/v2.0.2

**Comment by mmadrigalva** [comment]
It was fixed, thanks.
