### ISSUE TITLE
Could you support continuous  events of color changing?

### ISSUE THREAD

**Issue by Zcating** [scttcper/ngx-color#217]
As the title said...
I need to change the color continuously.
How can I do this?

**Comment by scttcper** [comment]
does it not do that?

**Comment by Zcating** [comment]
well, I mean that the '[onChangeComplete]' Output only changes the color when you finish moving the picker.
 Could you know some other ways or methods do this: '[onChangeComplete]' output changes color when you're moving?

**Comment by scttcper** [comment]
https://github.com/scttcper/ngx-color#onchange

**Comment by Zcating** [comment]
sorry, my fault. I should read it carefully...
