### ISSUE TITLE
Can't change default colors

### ISSUE THREAD

**Issue by gmerabishvili** [scttcper/ngx-color#218]
Hello. First of all thanks for this great library. I use twitter picker and I can't change the default colors of the picker. I want to change one of the colors from this default array but it doesn't work: ['#FF6900', '#FCB900', '#7BDCB5', '#00D084', '#8ED1FC', '#0693E3', '#ABB8C3', '#EB144C', '#F78DA7', '#9900EF']. Can you help me? I need it immediately.

**Comment by scttcper** [comment]
what have you tried?

**Comment by gmerabishvili** [comment]
oh, my bad. I was using color instead of colors with array. Thank you anyway. Great lib! <3

**Comment by fanguangjian** [comment]
`               <color-twitter  [color]="state"></color-twitter>

state = ['#FF6900', '#FCB900', '#7BDCB5', '#00D084', '#8ED1FC', '#0693E3', '#EB144C', '#F78DA7', '#9900EF'];
  state = [];
`
Hello, Scttcper. I have the same problem.  I use twitter picker and I can't change the default colors of the picker.

**Comment by fanguangjian** [comment]
I got it! Using  <color-twitter [colors]="state">
