### ISSUE TITLE
Modify css circle picker

### ISSUE THREAD

**Issue by Estevete** [scttcper/ngx-color#222]
How can I modfiy the CSS of the circle picker in order to center the circles? Because I'm trying to override it and nothing happens. Could you help me? I want to adapt it to my design.
Thanks.

**Comment by scttcper** [comment]
https://github.com/scttcper/ngx-color/blob/master/src/lib/components/circle/circle.component.ts#L37

try overriding .circle-picker in your non-scoped styles
