### ISSUE TITLE
Alpha selector visible after setting disableAlpha to true

### ISSUE THREAD

**Issue by pantos1** [scttcper/ngx-color#229]
Hi,

I'm using <color-sketch> in v 4.0.0. I set disabledAlpha to true and the alpha slider is still visible. It also changes the color in the preview.

![image](https://user-images.githubusercontent.com/18245665/64108505-3c6ea100-cd7d-11e9-8e69-c52e343ef1d8.png)

**Comment by scttcper** [comment]
thanks for reporting
