### ISSUE TITLE
Simple Shade Slider

### ISSUE THREAD

**Issue by SeijiV13** [scttcper/ngx-color#230]
Hi, I would like to suggest a new feature for the color slider, this is a simple shade slider. this is just like a hue slider but the start color is the selected color from hue slider  going to a darker color
![Capture](https://user-images.githubusercontent.com/10501521/64309167-44714f80-cfce-11e9-9d8d-dd8d7bee39d1.PNG)

**Comment by SeijiV13** [comment]
i've already worked on this and will request a PR

**Comment by scttcper** [comment]
Sounds good to me

**Comment by SeijiV13** [comment]
@scttcper already created a PR for this
