### ISSUE TITLE
Must call super constructor in derived class before accessing 'this' or returning from derived constructor

### ISSUE THREAD

**Issue by Fluqz** [scttcper/ngx-color#259]
Hey, when I include your color picker in my angular project, I get the following error:

> Must call super constructor in derived class before accessing 'this' or returning from derived constructor

This error only occurs on a live server. When compiling on my local machine, I donot see this error, only when compliling and upload via ftp.

In my app.module.ts I import the ColorCircleModule like so

`import { ColorCircleModule } from 'ngx-color/circle';
`

then import it like: 

`imports: [ColorCircleModule]`

and use it like so

`<color-circle width="120px" [colors]="wallColors" circleSize="30" circleSpacing="5" (onChangeComplete)="setWallColor($event)"></color-circle>`

where wallColors is a array of strings

`private wallColors: string[] = ['#e6e1c9', '#b34a59', '#...']`

**Comment by scttcper** [comment]
🤷‍♂
