### ISSUE TITLE
Support for SSR (Angular Universal)

### ISSUE THREAD

**Issue by maddy2894** [scttcper/ngx-color#260]
First of all, thank you for this great library. It works great in normal mode, but fails while running on SSR mode via angular universal.

The error i get is:
```Event is not defined``` 
on 
``` Object(tslib__WEBPACK_IMPORTED_MODULE_0__["__metadata"])("design:paramtypes", [Event, Number, Number, Object]),```
This error occurs after webpack compilation.

It would be great if this issue is fixed.

**Comment by scttcper** [comment]
should be working? i dunno
