### ISSUE TITLE
Transparency still possible with disableAlpha=true

### ISSUE THREAD

**Issue by aGautrain** [scttcper/ngx-color#268]
Hello,

Disabling alpha removes slider as expected (I'm using color-sketch implementation),

But if user types an HEX with a length of 4 such as 1230, it will be converted into a color of #112233 (which is normal behavior), but a transparency set to 0%.
It typically happens when user deletes some chars of a 6-length HEX, coming down to a HEX of 4 and so, transparency.

I think it's a way to bypass the behavior we expect when setting disableAlpha to TRUE.
What do you think ?

Thanks for your time

--
I can do a PR if needed, I've looked into code and it seems to be related with `isValidHex(hex: string)` / `handleChange` not taking into account disableAlpha attribute.

**Comment by vitokhangnguyen** [comment]
I am not sure I understand the title correctly but isn't that when `disableAlpha=false`, it is the default? Which means Alpha should be available.

It should be gone if  `disableAlpha=true`.

**Comment by aGautrain** [comment]
I've inverted false and true while explaining but the problem remains the same

Here is a screenshot (and it's easily reproducible) 
You can see there is no transparency slider (because disableAlpha is set to TRUE)
But it's still possible to create a transparent color (with a four-length hex code, last char matches transparency while it should not, as alpha is disabled)

<img width="321" alt="Screenshot 2020-02-25 at 11 30 32" src="https://user-images.githubusercontent.com/9020134/75239114-6223b280-57c2-11ea-8150-cfcb880ea692.png">

I've come across a custom solution myself where I remove that transparency when a color is emitted, but I think it should be included in ngx-color code directly.

**Comment by vitokhangnguyen** [comment]
Nice. I think you should make a PR about that. I am just going through this when I tried to use this component for my Angular app.
