### ISSUE TITLE
Cant pass new colors set to color-swatches component

### ISSUE THREAD

**Issue by davidecampello** [scttcper/ngx-color#277]
Hi, I would like to pass a custom set of colors to the color-swatches component but If I pass an array to the property colors I see only a white rectange.
This is an example
[https://stackblitz.com/edit/angular-ngx-colors-test](url)

Is it possibile to do this?
Thanks

**Comment by scttcper** [comment]
that is because you have defined colors incorrectly. 
you have `colors: [[]]`
it should be `colors = [[]]`

**Comment by davidecampello** [comment]
I'm sorry for this stupid error. Thanks for the answer
