### ISSUE TITLE
Color select does not work for color-circle with colors which are not given as default

### ISSUE THREAD

**Issue by sayedirfan** [scttcper/ngx-color#282]
I think it is a bug that when I specify color that are not default in this component, the selection does not work. For example:
 colors = ['#FF1744', '#AA0FFF', '#304FFE', '#1DE9B6', '#AEEA00', '#FF6D00', '#795548'];
Here only the color '#795548' is possible to select because it belongs to the default color set, the rest are just not getting selected upon click. 
 Check here in [stackblitz url](https://angular-ngx-colors-test-hy8dyd.stackblitz.io)

**Comment by scttcper** [comment]
Thanks for the stackblitz!

**Comment by sayedirfan** [comment]
> 🎉 This issue has been resolved in version 5.1.1 🎉
> 
> The release is available on:
> 
> * [npm package (@latest dist-tag)](https://www.npmjs.com/package/ngx-color/v/5.1.1)
> * [GitHub release](https://github.com/scttcper/ngx-color/releases/tag/v5.1.1)
> 
> Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot 📦🚀

Thanks a lot!
