### ISSUE TITLE
Hide / show colour picker

### ISSUE THREAD

**Issue by MatthewLHolden** [scttcper/ngx-color#318]
Question: Is it possible to not have the colour picker available constantly? I have a page where there will be up to 3 colour pickers and would like to click on each section to toggle the colour picker view and when clicking away from the colour picker, the selected colour picker will hide.

**Comment by scttcper** [comment]
this is left to the user to implement

**Comment by MatthewLHolden** [comment]
Thanks for the update: Might be a suggestion for the future like `ngx-color-picker` : https://zefoy.github.io/ngx-color-picker/
