### ISSUE TITLE
Access to color-swatches styles

### ISSUE THREAD

**Issue by andrzej-pakula** [scttcper/ngx-color#334]
Hi. How can I override the style of the .swatches-overflow class in a component
https://github.com/scttcper/ngx-color/blob/master/src/lib/components/swatches/swatches.component.ts#L42 ?

Best regards

**Comment by scttcper** [comment]
it is an input https://github.com/scttcper/ngx-color/blob/master/src/lib/components/swatches/swatches.component.ts#L70
