### ISSUE TITLE
Value accessor support

### ISSUE THREAD

**Issue by mmuenker** [scttcper/ngx-color#343]
It would be great if ngx-color would support for the value accessor concept of angular forms.

This would allow a simpler integration into a form.

```html
<color-block [(ngModel)]="widget.color"></color-block>
```

```html
<color-block formControlName="color"></color-block>
```

If I find some time in the next few days I will make a pull request with these changes.

**Comment by scttcper** [comment]
this is supported now right?

**Comment by mmuenker** [comment]
yes in version 7.2.0 this is supported.

https://stackblitz.com/edit/angular-ngx-color-value-accessor-demo?file=src/app/app.component.html
