### ISSUE TITLE
angular5 support

### ISSUE THREAD

**Issue by ramarro123** [scttcper/ngx-color#35]
hello,

is this module expected to work on angular5?

i got this exception

> Uncaught Error: Unexpected value 'ColorSketchModule' imported by the module 'AppModule'. Please add a @NgModule annotation.

not sure if it's for angular5 or for something stupid that i do :)

**Comment by scttcper** [comment]
I know how to fix that. I probably didn't deploy correctly. Hang tight will release a new version.

**Comment by scttcper** [comment]
should be fixed in `ngx-color@0.0.3`. Things are most likely still rough around the edges

**Comment by orionghf** [comment]
Hi, 
it also now gives this error  : 

`Uncaught Error: Unexpected value 'AlphaModule' imported by the module 'ColorSketchModule'. Please add a @NgModule annotation.`

**Comment by scttcper** [comment]
I'll check and try to fix it today. You might try --aot to get around it for now.

**Comment by scttcper** [comment]
alright 0.1.5 might be working. It worked for the component I tried against a new project w/ angular-cli. Finally have some free time soon to finish this project up and fix the publishing.
