### ISSUE TITLE
cannot use library on Angular v13

### ISSUE THREAD

**Issue by MADCAZ** [scttcper/ngx-color#362]
I start new project with v13 try to serve with import ColorTwitterModule in app.module

and I found this issue

<img width="901" alt="Screen Shot 2564-11-08 at 14 25 57" src="https://user-images.githubusercontent.com/9088059/140700766-d637ac68-b204-4f6b-b5a8-d6253208a83a.png">

environment
- OSX 12.0.1
- Angular 13
- ngx-color 7.3.1

**Comment by ghmj2417** [comment]
Same issue as others:

```
/mydir/node_modules/ngx-color/fesm2020/ngx-color.mjs:7:0-44 - Error: Module not found: Error: Can't resolve '@ctrl/tinycolor' in '/mydir/node_modules/ngx-color/fesm2020'
```
