### ISSUE TITLE
Cannot find module 'ngx-color/chrome' or its corresponding type declarations.

### ISSUE THREAD

**Issue by Lucilor** [scttcper/ngx-color#370]
Got this error after upgarding to `ngx-color@8.0.0`. I have to copy the `chrome` folder from previous version to make it work.

**Comment by spicemix** [comment]
I don't get 

`import { ColorCircleModule } from 'ngx-color/circle';`

Either. Broken release.

**Comment by Timebutt** [comment]
Same here, looks like all sub exports have not been published in this release.

**Comment by scttcper** [comment]
circleci seems to be having some issues, but it should be fixed whenever it runs

**Comment by spicemix** [comment]
Now I'm getting a Module build failure along the lines of 

```
./node_modules/ngx-color/fesm2020/ngx-color-circle.mjs
 - Error: Module build failed (from ./node_modules/@angular-devkit/build-angular/src/babel/webpack-loader.js):
TypeError: .../node_modules/ngx-color/fesm2020/ngx-color-circle.mjs: (0 , _genMapping.maybeAddMapping) is not a function
at SourceMap.mark (.../node_modules/@babel/core/node_modules/@babel/generator/lib/source-map.js:49:37)
...
```
